version: '3.9'

services:
  vy2-be-voucher:
    container_name: vy2-be-voucher
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1001:1001"
      - "1002:1002"
      - "1003:1003"
      - "1004:1004"
      - "1005:1005"
      - "1006:1006"
      - "1007:1007"
      - "1008:1008"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
