version: '3.9'

services:
  vy2-be-voucher:
    container_name: vy2-be-voucher
    depends_on:
      - vy2-redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
