apiVersion: v1
kind: Secret
metadata:
  name: secret.be-voucher-traveloka
  namespace: traveloka-app
type: Opaque
data:
  JWT_SECRET: TUlJQlhqQ0NBUVNnQXdJQkFnSUdBWHZ5a3VNS01Bb0dDQ3FHU000OUJBTUNNRFl4TkRBeUJnTlZCQU1NSzNOcFFYQk5PWHBCZGsxVmFYaFhWV1ZHYUd0alpYZzFOakpSUnpGeVFVaFhhVjk2VWxGUVRWcFFhRzh3SGhjTk1qRXdPVEUzTURjd05URTNXaGNOTWpJd056RTBNRGN3TlRFM1dqQTJNVFF3TWdZRFZRUUREQ3R6YVVGd1RUbDZRWFpOVldsNFYxVmxSbWhyWTJWNE5UWXlVVWN4Y2tGSVYybGZlbEpSVUUxYVVHaHZNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUU4UGJQdkN2NUQ1eEJGSEVabEJwL3E1T0VVeW1xN1JJZ1dJaTd0a2w5YUdTcFlFMzVVSCtrQktEbnBoSk8zb2RwUFo1Z3ZnS3MybndSV2NyRG5VallMREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMXl5TVRSZTY2TWhFWElEOSt1VnViN3dvTWtOWWQwTGhTSHdLU1BNVVVUa0NJRlFHc2ZtMWVjWE9wZUdPdWZBaHYrQTFRV1pNdVRXcVl0K3VoL1lTUk5Ebg==
  DB_URI: bXNzcWw6Ly9zYTpWb3ZhbmhvYW5ndHVhbjFAc3Fsc2VydmVyOjE0MzMvdm91Y2hlcl9kZXZlbG9w
  REDIS_URI: cmVkaXM6Ly9yZWRpcy1zdGFnaW5nOjYzODA=
  PAYPAL_SECRET: RUF0OC1ydzBPT3JqOVVqX2JReDc5UTRoSzVwNGM3LUMwcXIzbk5EbU5MUmxSSFNBVlNNRHRvb2FpWEFVQzRVWktjTllmQnVzam5QRHNxdnU=
  PAYPAL_CLIENT_ID: QVN1YndMZnJfeDMwRGhreFo4aVdmSEctaXBKUEV0ekpBNUJtV2hmNXJ4YU9tM3laQmdKWVFZQk1vUmE0V18wVVZyREVDSFRVX0dvM2VfLWs=
  TOKEN_TELEGRAM: NTA5NTQ1MDE1NzpBQUc4aHhQcjZKRF9wVzlHbXdsa0J1WEozLUZkZ2NRYk5NOA==
  GROUP_TELEGRAM: LTYxNjczMjk1OQ==
