apiVersion: v1
kind: Service
metadata:
  name: be-voucher-traveloka
  namespace: traveloka-app
spec:
  selector:
    app: be-voucher-traveloka
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 30002
  type: NodePort